name: Process Images and Docs

on:
  push:
    branches:
      - main
    paths:
      - 'img/**' # Se activa con cualquier cambio en img/ para asegurar que detecte .PNG, .png, etc.

permissions:
  contents: write # Permiso vital para que el bot pueda guardar los cambios (push)

jobs:
  convert_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Obtener todo el historial para una comparación de archivos adecuada

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install Pillow
          pip install python-docx

      - name: Run Processing Scripts
        id: processing_scripts
        run: |
          python python/convert_to_jpg.py img/
          python python/generate_word.py

      - name: Check for changes and commit
        id: git_status
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add img/ # Stage all new files, modifications, and deletions in the img folder
          git diff-index --quiet HEAD || git commit -m "Auto: Generate previews and Word docs [skip ci]"
          git push || echo "No changes to commit or push" # Push solo si hay cambios, y no fallar si no hay